language: C

before_script:
  - uname -a
  - sudo apt-get update -q
  - sudo apt-get install -q coq
  - coqc --version
  - echo | coqtop

script:
  - cat Overture.v
  - cat HomFunctor2.v
  - coq_makefile Overture.v HomFunctor2.v -R . HoTT | make -f -
  - coqdoc -utf8 -html -R . HoTT HomFunctor2.v
  - cat HoTT.HomFunctor2.html
  - grep '<a name="lab2">' HoTT.HomFunctor2.html
  - grep --color='auto' -P -n "[\x80-\xFF]" HoTT.HomFunctor2.html
